name: face_verification
description: On-device face verification using FaceNet-style embeddings with an offline TFLite model for Flutter (Android/iOS).
version: 0.3.4
homepage: https://github.com/bhanuka96/face_verification
repository: https://github.com/bhanuka96/face_verification
issue_tracker: https://github.com/bhanuka96/face_verification/issues

environment:
  sdk: ^3.8.1
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  google_mlkit_face_detection: ^0.13.1
  tflite_flutter: ^0.12.1
  path: ^1.9.1
  image: ^4.7.2
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  pool: ^1.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/models/
